### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by stoivo** [clickatell/clickatell-ruby#1]
How are you supposed to use this in a rails app? Copy the file into my app? 

thx

**Comment by zachmanpro** [comment]
Hi Simon

This is a collection of ruby example scripts that uses Clickatell HTTP and Rest APIs.

To use the examples you require the rest-client gem:   

gem install rest-client

So you are welcome to copy the example files into your app if you like, but you’ll probably have to change it quite a bit to fit your solution seeing as the intention with these scripts was to help get you started.

**Comment by stoivo** [comment]
thx, I think I will just copy the things I need.

What I really wanted to know is if there is a option to to

``` ruby
# in initializer 
Clickatell.config.username = 'username'
Clickatell.config.passward = 'password'
Clickatell.config.api_key = 'key'

# in my class
require 'clickatell'

Clickatell.send('093139231', ' Here come some msg')
Clickatell.get_reminding_sms 
``
```

**Comment by zachmanpro** [comment]
No worries,

The examples don't include any Clickatell class that you can use like that, they are just simple instances of the RestClient class, so you are limited to the API of that gem. See https://github.com/rest-client/rest-client.

You can always write your own Clickatell wrapper class that will keep things nicely abstracted.

**Comment by stoivo** [comment]
yes, thx so much! :sparkles:
